# Generated by Django 5.2.1 on 2025-06-06 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('synonym', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_number', models.CharField()),
                ('abbreviation', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskPhoneNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasker.tasks')),
            ],
        ),
        migrations.CreateModel(
            name='TaskPersons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internet_account', models.CharField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasker.tasks')),
            ],
        ),
        migrations.CreateModel(
            name='TaskInternetAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internet_account', models.CharField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasker.tasks')),
            ],
        ),
        migrations.CreateModel(
            name='TaskEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasker.tasks')),
            ],
        ),
        migrations.AddField(
            model_name='tasks',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasker.tasksubjects'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasker.users'),
        ),
    ]
