# Generated by Django 5.2.1 on 2025-06-06 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskpersons',
            old_name='internet_account',
            new_name='person',
        ),
    ]
