# Generated by Django 5.2.1 on 2025-06-06 13:57

import django.db.models.deletion
import tasker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0002_rename_internet_account_taskpersons_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField()),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='user_number',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasker.taskstatus'),
        ),
    ]
