# Generated by Django 5.2.1 on 2025-06-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0003_taskstatus_alter_users_user_number_tasks_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='InternetAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='taskinternetaccounts',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskpersons',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskphonenumbers',
            name='task',
        ),
        migrations.AddField(
            model_name='tasks',
            name='emails',
            field=models.ManyToManyField(to='tasker.emails'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='accounts',
            field=models.ManyToManyField(to='tasker.internetaccounts'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='persons',
            field=models.ManyToManyField(to='tasker.persons'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='phoneNumbers',
            field=models.ManyToManyField(to='tasker.phonenumbers'),
        ),
        migrations.DeleteModel(
            name='TaskEmails',
        ),
        migrations.DeleteModel(
            name='TaskInternetAccounts',
        ),
        migrations.DeleteModel(
            name='TaskPersons',
        ),
        migrations.DeleteModel(
            name='TaskPhoneNumbers',
        ),
    ]
