# Generated by Django 5.2.1 on 2025-06-09 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0004_emails_internetaccounts_persons_phonenumbers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internetaccounts',
            old_name='account',
            new_name='account',
        ),
    ]
