# Generated by Django 5.2.1 on 2025-06-09 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0005_rename_url_internetaccounts_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internetaccounts',
            old_name='account',
            new_name='account',
        ),
    ]
