# Generated by Django 5.2.1 on 2025-06-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0006_rename_account_internetaccounts_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumbers',
            name='numbers',
            field=models.CharField(),
        ),
    ]
