# Generated by Django 5.2.1 on 2025-06-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0007_alter_phonenumbers_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='email',
            field=models.CharField(),
        ),
    ]
