# Generated by Django 5.2.1 on 2025-06-18 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0009_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
