# Generated by Django 5.2.1 on 2025-06-18 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0012_customuser_alter_tasks_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
