# Generated by Django 5.2.1 on 2025-06-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0013_delete_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatus',
            name='synonym',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasksubjects',
            name='synonym',
            field=models.CharField(default=''),
        ),
    ]
