# Generated by Django 5.2.1 on 2025-06-18 11:55

from django.db import migrations, models

def add_default_statuses(apps, schema_editor):
    TaskStatus = apps.get_model('tasker', 'TaskStatus')
    default_statuses = [
        {"synonym": "Новое", "status": "new"},
        {"synonym": "В работе", "status": "in_progress"},
        {"synonym": "Проверка", "status": "review"},
        {"synonym": "Доработка", "status": "revision"},
        {"synonym": "Завершено", "status": "complete"},
        {"synonym": "Отменено", "status": "cancel"},
    ]
    for data in default_statuses:
        TaskStatus.objects.get_or_create(**data)

class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0014_taskstatus_synonym_alter_tasksubjects_synonym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksubjects',
            name='synonym',
            field=models.CharField(),
        ),
        migrations.RunPython(add_default_statuses),
    ]
