# Generated by Django 5.2.1 on 2025-06-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0015_alter_tasksubjects_synonym'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='task_files/', verbose_name='Прикрепленный файл'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
