# Generated by Django 5.2.1 on 2025-06-21 13:44

import django.db.models.deletion
import tasker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0016_tasks_file_tasks_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.ForeignKey(default=tasker.models.get_new_status, on_delete=django.db.models.deletion.PROTECT, to='tasker.taskstatus'),
        ),
    ]
